### ISSUE TITLE
Questions: Name of elasticsearch.index and TimeMachine

### ISSUE THREAD

**Issue by spamwax** [Ellerhold/fs2es-indexer#11]
- Does it matter what is used for `elasticsearch.index` in `config.yml`?
  Do I need to somehow communicate that name with Samba so it knows what index to look for in elasticsearch?
- Since macOS creates sparse bundles on Samba for TimeMachine, does it make sense to try to index that TimeMachine share using `elasticsearch`/`fs2es` or there is no way to parse the content of bundle and I should just rely on macOS's finder/spotlight to do the indexing over network?

**Comment by MatthiasKuehneEllerhold** [comment]
Samba searches in all indizes on the elasticsearch instance. So it doesnt matter which index you define. 

This index should NOT be used for anything else than fs2es though, because it'll delete all documents not matching my queries.

Timemachine createse a X.sparsebundle directory that contains a "bands" directory with a 4-character hash file that contains a binary content.

So all fs2es would see is `X.sparsebundle/bands/3ad3`. Thats not really helpful for the spotlight-search. 

So I'd exclude all sparsebundle from fs2es.
