### ISSUE TITLE
Enabling indexing fails

### ISSUE THREAD

**Issue by elfranne** [Ellerhold/fs2es-indexer#2]
When trying to enable indexing (on a client) I get this info:
```bash
sudo mdutil -i on /Volumes/[share]
/System/Volumes/Data/Volumes/[share]:
Error: unable to perform operation.  (-403)
	Server search enabled.
```

On the SMB server the index process seems to have worked fine: 
```log
[...]
2021-12-02 14:06:44 - Files & directories indexed: 1085039
2021-12-02 14:06:45 - Refreshing index "files" ...
2021-12-02 14:06:48 - Index "files" successfully refreshed
2021-12-02 14:06:48 - Deleting old documents from "files" ...
2021-12-02 14:06:52 - Deleted 13656 old documents from "files"
2021-12-02 14:06:52 - Indexing run done after 5.88 minutes.
```

The Samba config:
```
[global]
spotlight backend = elasticsearch
elasticsearch:address = localhost
elasticsearch:port = 9200

[...]

[share]
spotlight = yes

```

Is there anything I am missing ?

Source: 
https://wiki.samba.org/index.php/Spotlight_with_Elasticsearch_Backend
https://www.samba.org/samba/docs/current/man-html/smb.conf.5.html

**Comment by chrisfield490** [comment]
Just an idea, which I am trying myself, but it might be worth adding elasticsearch:index = _nameofindex_ to your global config. As it just occurred to me how will samba know which index to use. Shame its not in the samba wiki documentation. I don't know if it will fix your issue, but it might help.

**Comment by MatthiasKuehneEllerhold** [comment]
First the basic questions:
Which version of Mac OS are you using?
Which version of samba (on the server) are you using?
Is there anything in the samba-log? There should be!

More project-related:
Can you verify that the elastic search index is built properly? Try retrieving some documents either via kibana or via CURL from your elasticsearch instance.

**Comment by elfranne** [comment]
Mac version : 11.6.1

Ubuntu 20.04
samba: 2:4.13.14+dfsg-0ubuntu0.20.04.2 (latest on official repo)

This is the only samba log i get when i run the `mdutil` command:
```log
[2021/12/02 15:33:52.711887,  3] ../../source3/smbd/trans2.c:3637(smbd_do_qfsinfo)
  smbd_do_qfsinfo: level = 1003
[2021/12/02 15:33:52.716281,  3] ../../source3/smbd/trans2.c:3637(smbd_do_qfsinfo)
  smbd_do_qfsinfo: level = 1003
```

Using curl I grabbed a random document in ElasticSearch:
```json
{
  "_index" : "files",
  "_type" : "_doc",
  "_id" : "ff4cfac027fcd4489316b23455d582542a3dc295",
  "_version" : 380,
  "_seq_no" : 414257084,
  "_primary_term" : 1,
  "found" : true,
  "_source" : {
    "path" : {
      "real" : "/mnt/BACKUP/test"
    },
    "file" : {
      "filename" : "test"
    },
    "time" : 1.6385220021510236E9
  }
}
```
I ll try to enable debug log on ElasticSearch to see the requests being made.

**Comment by chrisfield490** [comment]
I am having the same problem, I am running ubuntu 20.04 LTS with samba 4.13.15-Ubuntu.
I too am able to get a result against a elasticsearch query in curl. But not on my macs. My macs are 10.13 through to the latest release and they do not get a result from the search.
I have set my log level to 1 and there is nothing in the samba logs nor in the log file for the user themselves.

**Comment by elfranne** [comment]
Tried to log queries on ES but apparently it s a [paid feature](https://stackoverflow.com/a/41673321)

Setting slowlog to 0ms does not log anything:
```
curl -X "PUT" "http://localhost:9200/files/_settings" \
     -H 'Content-Type: application/json; charset=utf-8' \
     -d $'{
  "index": {
    "search.slowlog.threshold.query.trace": "0ms",
    "search.slowlog.threshold.fetch.trace": "0ms",
    "search.slowlog.level": "trace"
  }
}'
```

Removing the settings:
```
curl -X "PUT" "http://localhost:9200/files/_settings" \
     -H 'Content-Type: application/json; charset=utf-8' \
     -d $'{
  "index": {
    "search.slowlog.threshold.query.trace": null,
    "search.slowlog.threshold.fetch.trace": null,
    "search.slowlog.level": null
  }
}'
```

**Comment by MatthiasKuehneEllerhold** [comment]
Ive tested a little bit and I can confirm it works:
```
$ sudo mdutil -s /Volumes/my-mount
/System/Volumes/Data/Volumes/my-mount:
     Server search enabled.

$ mdfind -onlyin /Volumes/my-mount -name "test"
/System/Volumes/Data/Volumes/my-mount/test.txt

$ smbutil statshares -a
my-mount
                              SERVER_NAME                   fileserver.localhost.lan
                              USER_ID                       502
                              SMB_NEGOTIATE                 SMBV_NEG_SMB1_ENABLED
                              SMB_NEGOTIATE                 SMBV_NEG_SMB2_ENABLED
                              SMB_NEGOTIATE                 SMBV_NEG_SMB3_ENABLED
                              SMB_VERSION                   SMB_3.1.1
                              SMB_ENCRYPT_ALGORITHMS        AES_128_CCM_ENABLED
                              SMB_ENCRYPT_ALGORITHMS        AES_128_GCM_ENABLED
                              SMB_ENCRYPT_ALGORITHMS        AES_256_CCM_ENABLED
                              SMB_ENCRYPT_ALGORITHMS        AES_256_GCM_ENABLED
                              SMB_CURR_ENCRYPT_ALGORITHM    OFF
                              SMB_SHARE_TYPE                DISK
                              SIGNING_SUPPORTED             TRUE
                              EXTENDED_SECURITY_SUPPORTED   TRUE
                              UNIX_SUPPORT                  TRUE
                              LARGE_FILE_SUPPORTED          TRUE
                              OS_X_SERVER                   TRUE
                              FILE_IDS_SUPPORTED            TRUE
                              DFS_SUPPORTED                 TRUE
                              FILE_LEASING_SUPPORTED        TRUE
                              MULTI_CREDIT_SUPPORTED        TRUE
```

This is done on a Mac OS 12.0.1 (Monterey) against an debian buster fileserver with a samba 4.14.10 .

**Comment by chrisfield490** [comment]
I am running this on a mac running 10.13.6 and these are my results.
```
mdutil -s /Volumes/my-mount
/Volumes/my-mount:
	Server search enabled.

mdfind -onlyin /Volumes/my-mount-name "myname"
no value returned (yet under curl to elastic search returns values)

Design_Library                
                              SERVER_NAME                   myservername
                              USER_ID                       108327420
                              SMB_NEGOTIATE                 SMBV_NEG_SMB1_ENABLED
                              SMB_NEGOTIATE                 SMBV_NEG_SMB2_ENABLED
                              SMB_NEGOTIATE                 SMBV_NEG_SMB3_ENABLED
                              SMB_VERSION                   SMB_3.02
                              SMB_SHARE_TYPE                DISK
                              SIGNING_SUPPORTED             TRUE
                              EXTENDED_SECURITY_SUPPORTED   TRUE
                              UNIX_SUPPORT                  TRUE
                              LARGE_FILE_SUPPORTED          TRUE
                              OS_X_SERVER                   TRUE
                              DFS_SUPPORTED                 TRUE
                              FILE_LEASING_SUPPORTED        TRUE
                              MULTI_CREDIT_SUPPORTED        TRUE
                              ENCRYPTION_SUPPORTED          TRUE
```
One thing i have noticed is that the linux partition is named like /2021my-mount-name but in samba is shared as my-mount-name. Could this be causing issues.

As in the elasticsearch gc.log file we can see responses like this when we do a spotlight search: [2021-12-03T11:54:19.344+0000][945][safepoint   ] Safepoint "Cleanup", Time since last: 160013524985 ns, Reaching safepoint: 131066 ns, At safepoint: 5805 ns, Total: 136871 ns

**Comment by elfranne** [comment]
So it seems you should not enable (local) indexing with `sudo mdutil -i on /Volumes/[share]`

The `mdfind` works fine after the 2nd try. The Spotlight does, however, not show any results.
(I basically have a week experience with mac OS so might be me)

**Comment by chrisfield490** [comment]
> So it seems you should not enable (local) indexing with `sudo mdutil -i on /Volumes/[share]`
> 
> The `mdfind` works fine after the 2nd try. The Spotlight does, however, not show any results. (I basically have a week experience with mac OS so might be me)

What is puzzling, if you specify tracker rather than elasticsearch for your spotlight backend, when you run mdutil -s /Volume/my-volume it reports that Indexing is disabled. Which is what i was expecting by specifying elasticsearch

**Comment by MatthiasKuehneEllerhold** [comment]
For tracker to work correctly you have to manually compile your samba server with a few extra options, configure it all and let it run.
I got it working but it was nowhere near as easy as the elasticsearch integration.

> The Spotlight does, however, not show any results
Do you mean the finder? What are you doing exactly? I go

- Open Finder
- Mount the Share (if not already mounted)
- Go to the share root
- Type a known filename into the field at the top right
- Below the tabs (above the directory and file list) there is a search bar, make sure that the server / the share is selected. Otherwise itll only search your mac (or the whole network!)

**Comment by elfranne** [comment]
So I was using the Spotlight :mag_right:  near the clock at the top bar. After talking with more experienced Mac user he told me that one only use local Spotlight DB.

If I use the search in Finder, it works fine !

`mdutil` can be a bit confusing, Indexing is enabled on local disk and server search is enabled on smb shares:
```
mdutil -sa              
/:
	Indexing enabled. 
/System/Volumes/Data:
	Indexing enabled. 
/Volumes/share1:
	Server search enabled.
/Volumes/share2:
	Server search enabled.
```

**Comment by MatthiasKuehneEllerhold** [comment]
Nice :)

**Comment by elfranne** [comment]
Leaving this open for @chrisfield490 . Works for me.

**Comment by chrisfield490** [comment]
> For tracker to work correctly you have to manually compile your samba server with a few extra options, configure it all and let it run. I got it working but it was nowhere near as easy as the elasticsearch integration.
> 
> > The Spotlight does, however, not show any results
> 
> Do you mean the finder? What are you doing exactly? I'm doing
> 
> * Open Finder
> * Mount the Share (if not already mounted)
> * Go to the share root
> * Type a known filename into the field at the top right
> * Below the tabs (above the directory and file list) there is a search bar, make sure that the share (!) is selected. Otherwise itll only search your mac (or the whole network!)
> * Wait a second or 20

When you mention tracker, are you talking about gnome-tracker, or elasticsearch. As we are using tracker on another Ubuntu server where it does work, but we want to use elastic as it is faster.

**Comment by elfranne** [comment]
Also thanks @MatthiasKuehneEllerhold  for the help and the indexer !

**Comment by MatthiasKuehneEllerhold** [comment]
Gnome-Tracker: https://wiki.samba.org/index.php/Spotlight_with_Gnome_Tracker_Backend

**Comment by chrisfield490** [comment]
> Gnome-Tracker: https://wiki.samba.org/index.php/Spotlight_with_Gnome_Tracker_Backend

Aah. So tracker is still needed for the elasticsearch option. 
Thank you.

**Comment by elfranne** [comment]
I did not install gnome-tracker.

**Comment by chrisfield490** [comment]
> I did not install gnome-tracker.

Now im confused. Ubuntu samba already supports spotlight backend, we installed gnome-tracker to confirm that the searches do work, and now we to use elasticsearch.

We are just missing one step, as we can see samba is connecting the elastic search, but is not retrieving anything.

**Comment by elfranne** [comment]
My  elasticsearch is dedicated only to indexing, with no authentication, ssl, etc... but is exposed only to localhost.
Can you see the request being made to elasticsearch? And the response?
You can try to TCPdump the requests?

**Comment by chrisfield490** [comment]
> My elasticsearch is dedicated only to indexing, with no authentication, ssl, etc... but is exposed only to localhost. Can you see the request being made to elasticsearch? And the response? You can try to TCPdump the requests?

Mine is set the exact same way, no authentication or ssl. Only available to localhost. when i read the gc.log from elasticsearch we can see a connection is being closed when we do our search, even with debug on there is very little information in the logs.

**Comment by elfranne** [comment]
Yes I use the default Samba from Ubuntu 20.04 but I installed Elasticsearch from the upstream repo not the Ubuntu repo... Not sure if this relevant. The upstream includes xpack, a closed source plug-in if not mistaken.

**Comment by MatthiasKuehneEllerhold** [comment]
No Gnome-Tracker is *NOT* needed for elasticsearch!

**Comment by MatthiasKuehneEllerhold** [comment]
@chrisfield490 I gather its still not working?
* You have Samba 4.12 or later?
* You have configured your smb.conf to include the above lines?
* Your elasticsearch is up and running under the specified IP and port (e. g. localhost : 9200)?
* The indexer is set up correctly and creates elasticsearch documents?
* Can you retrieves documents from the elasticsearch instance manually (via curl or kibana)?
* Does the search via the finder work with a known file?
* What does mdutil -s /path/to/share output?
* Does mdfind -onlyin /path/to/share known-file output?

**Comment by chrisfield490** [comment]
My version of ubuntu 20.04 would of been upgraded to 4.12, so i removed all samba packages and re-installed samba again with apt-get install samba.
i have configured my smb.conf to use these settings in the global
spotlight backend = elasticsearch
                                elasticsearch:address = localhost
                                elasticsearch:port = 9200

and in my share spotlight = yes

indexer is correct and shows it is indexing files.
The search from the mac command line using mdfind -onlyin /path/to/share immediately returns nothing, and the finder search on the volume returns no values. When i run curl -X POST -H "Content-Type: application/json" http://localhost:9200/_search -d '{"query":{"query_string":{"query":"dumpbin"}}}' on the machine, elastic returns results of matching items.

mdutil -s /path/to/share returns its a server search enabled

So we can see the fs2es-indexer is doing exactly what it was asked, it just seems to be getting results from elasticsearch via samba is the issue.

**Comment by MatthiasKuehneEllerhold** [comment]
So is your samba version 4.12+ ?

If samba <=> elasticsearch does not work propery you can look into the samba logs to try to figure out what went wrong.
Sometimes a restart of smbd / elasticsearch works wonders. Samba seems to cache the "connection state" to ES aggresivly...

**Comment by chrisfield490** [comment]
> So is your samba version 4.12+ ?
> 
> If samba <=> elasticsearch does not work propery you can look into the samba logs to try to figure out what went wrong. Sometimes a restart of smbd / elasticsearch works wonders. Samba seems to cache the "connection state" to ES aggresivly...

I have just built another ubuntu server and run an index, but still unable to do a spotlight search. I used this link from digital ocean to install a package of elasticsearch https://www.digitalocean.com/community/tutorials/how-to-install-and-configure-elasticsearch-on-ubuntu-20-04, a fresh install of samba on ubuntu is 4.13.14-Ubuntu.

I will keep looking to see why samba does not recognise elastic for spotlight search on my machines

**Comment by chrisfield490** [comment]
I am able to close the ticket now. The fault is part end user and permission related. Run  this on a test machine, and all working now.

**Comment by elfranne** [comment]
What was the permission issue? other could use that info.

**Comment by chrisfield490** [comment]
> What was the permission issue? other could use that info.

The permissions on the volume were set to 700 with root:root. So i changed the folder structure permissions recursively to 755 and suddenly my searches on the mac were returning results.

**Comment by lamixer** [comment]
Hello... Perhaps I could continue this. I have a similar set up to chrisfield490 and similar problems. The permissions (on MacOS) I use to mount the share is the owner is my MacOS account user who has Read & Write Privilege, and everyone has No Access. In MacOS terminal, viewing from /Volumes, shows drwx------ username staff.

Should this work? Thanks.

**Comment by MatthiasKuehneEllerhold** [comment]
Sorry I dont understand your problem and how it relates to the indexer.
On the file server you have set your files to 0700 (only accessible by the user).
Mounted on MacOS it shows 0700? That is correct ...

Running the indexer als root *or* the user with read access should properly index the files and put all documents into elasticsearch. After this you should be able to search for them via Spotlight in the MacOS finder.

**Comment by chrisfield490** [comment]
> Hello... Perhaps I could continue this. I have a similar set up to chrisfield490 and similar problems. The permissions (on MacOS) I use to mount the share is the owner is my MacOS account user who has Read & Write Privilege, and everyone has No Access. In MacOS terminal, viewing from /Volumes, shows drwx------ username staff.
> 
> Should this work? Thanks.

I am using sudo users on my ubuntu server that is performing the share. So setting the volume to share with the macs to rwxr-xr-x in ubuntu, allowed fs2es-indexer to be able to perform the searches via the mac.

0700 could be stopping the service from running. Hope this information is useful.

**Comment by lifepillar** [comment]
Do you have to configure something client-side to get `Server search enabled` from `mdutil` (macOS Monterey)? I have a pretty vanilla Samba server with Elasticsearch and `mdutil` shows `Indexing and searching disabled` (and I get no results from the Finder). If I enable it with `mdutil -i on /Volumes/share`, then I get search results, but my understanding is that then a local db is used. On another machine with High Sierra, `mdutil` returns `Indexing disabled`, and yet searches return results, but I am not sure it's relying on server's search. That's pretty confusing…

**Comment by chrisfield490** [comment]
> Do you have to configure something client-side to get `Server search enabled` from `mdutil` (macOS Monterey)? I have a pretty vanilla Samba server with Elasticsearch and `mdutil` shows `Indexing and searching disabled` (and I get no results from the Finder). If I enable it with `mdutil -i on /Volumes/share`, then I get search results, but my understanding is that then a local db is used. On another machine with High Sierra, `mdutil` returns `Indexing disabled`, and yet searches return results, but I am not sure it's relying on server's search. That's pretty confusing…

Have you installed vfs fruit. this should be a standard part of samba on Ubuntu 20.04 LTS and helps the macs use the samba share.
Do your samba global settings include these option:
                               spotlight backend = elasticsearch
                                elasticsearch:address = localhost
                                elasticsearch:port = 9200
  Under your share name, have you set: spotlight = yes.
  
 I have these options enabled and when we run mdutil -s /Volumes/SharedVolume it shows "Server search enabled".

Can you confirm that you have run your scan and have performed a search of the elastic database using curl, and have had results returned for your search?

**Comment by lifepillar** [comment]
I'd say “yes” to all questions. FYI, my server runs on FreeBSD, but that should not matter. I have just (re)made a fresh install of a Samba server. These are the details:

>Have you installed vfs fruit. this should be a standard part of samba

I have Samba 4.13.14. I have not explicitly installed any package for vfs fruit, but as you say, it should be a standard part of Samba. I do have `fruit.so` and many other libraries under `/usr/local/lib/samba4/modules/vfs`.

>Do your samba global settings include these option

Yes. This is my full Samba configuration:

```
[global]
server role = standalone server
workgroup = WORKGROUP
min protocol = SMB2
ea support = yes
vfs objects = catia fruit streams_xattr zfsacl
fruit:aapl = yes
fruit:advertise_fullsync = true
fruit:delete_empty_adfiles = yes
fruit:encoding = native
fruit:metadata = stream
fruit:model = MacSamba
fruit:nfs_aces = no
fruit:veto_appledouble = no
fruit:posix_rename = yes
fruit:zero_file_id = yes
fruit:wipe_intentionally_left_blank_rfork = yes
security = user
passdb backend = tdbsam
acl allow execute always = yes
spotlight backend = elasticsearch
elasticsearch:address = 127.0.0.1
elasticsearch:port = 9200

[MyShare]
path = /var/data
valid users = me
writable = yes
browsable = yes
read only = no
guest ok = no
public = no
create mask = 0666
directory mask = 0755
fruit:resource = file
spotlight = yes
```

I have run `fs2es-indexer index` with default `config.yml` except that I have of course changed the directory to be indexed to `/var/data`. No errors.

The share contains a file named `hello.txt`, and this is what I get when I run `curl`:

```
$ curl -X POST -H "Content-Type: application/json" http://localhost:9200/_search -d '{"query":{"query_string":{"1 ":"hello.txt"}}}'
{"took":1,"timed_out":false,"_shards":{"total":1,"successful":1,"skipped":0,"failed":0},"hits":{"total":{"value":1,"relation":"eq"},"max_score":0.9808291,"hits":[{"_index":"files","_type":"_doc","_id":"c43ac2ef5d6e69653ecff75abe8e0bfbddebecf7","_score":0.9808291,"_source":{"path":{"real":"/var/data/hello.txt"},"file":{"filename":"hello.txt"},"time":1641662268.4816651}}]}}
```

Running `mdutil -s /Volumes/MyShare` in both my macOS clients (macOS 12.0.1 and macOS 10.13.6, respectively) returns in both cases `Indexing disabled` (note: it's *not* `Indexing and searching disabled`!). If I search for for a *prefix* of `hello` or `txt` in the Finder (e.g., `he` or `tx`), the Finder finds it—but not if I search for a substring (e.g., `llo` or `xt`): this looks like standard Spotlight's behavior. If I search for a word contained in the text file, nothing is found: my understanding is that this would be expected if server search were used, as `fs2es-indexer` does not index the file's content (right?)—but it is also expected if Spotlight indexing is off.

What I have just described is consistent in both clients.

In my previous post, I had executed `mdutil -d /Volumes/MyShare` in one client, which changes the status to `Indexing and searching disabled`. That's why I did not get any results. I can enable (local) Spotlight indexing with `mdutil -i on`: that sets the status to `Indexing enabled`, and then I can exploit the full potential of Spotlight (i.e., searching in files' contents), but, of course, only in the machine where indexing has been enabled (Spotlight index is stored locally, not on the share). I can use `mdutil -i off` to turn off  indexing, but keep search enabled: the status goes back to the initial `Indexing disabled`.

Anyway, I am not seeing `Server search enabled`.

I did another experiment: I copied more files into the share and (*without* `fs2es-indexer` running server-side) and I tried some searches—and they worked with the same behaviour as above.

So, what I see is that (basic) search happens *only* client-side (i.e., Spotlight *search* is enabled), but by default the content of the share is not indexed (Spotlight *indexing* is disabled).

So, the question is: what can I do to enable search server-side, or to debug the reason why it is not enabled?

For completeness, this is my `elasticsearch.yml`:

```
cluster.name: samba               
node.name: node1                  
path.data: /var/db/elasticsearch  
path.logs: /var/log/elasticsearch 
network.host: 127.0.0.1           
http.port: 9200                   
xpack.ml.enabled: false           
discovery.type: single-node       
```

**Comment by lifepillar** [comment]
>my server runs on FreeBSD, but that should not matter

Or maybe it does. I can't find anything wrong with my configuration.

**Comment by lamixer** [comment]
I was waiting until I was more sure of this answer, but since you seem to be working on it now, I'll offer it. 

From the Mac, when you cd to to /Volumes/your-share/ and look at the files and folders therein, what permissions do you have?

I had rwx------ for files and drwx------ for folders, or viewed from Finder (get info) my mac user account is read+write but there was no entry for system and for everyone was no access.

I ran into this situation because I was playing with my SMB.conf (and fruit options) and "fruit:nfs_aces = no" caused this situation. Restoring a more default set up including "fruit:nfs_aces = yes" (default) caused a more normal MacOS permisssions scheme inside my mounted samba share (files were not executable, there were group read permissions). At this point I was able to do a Spotlight search on the share. I did not double-check using mdutil -i to see what type of search was happening (server side or ???).

Sorry, I'm not looking at the machine right now.

I'm on Catalina and Samba is 4.13.13 on Debian (Proxmox actually).

**Comment by lifepillar** [comment]
I think the problem is that Samba on FreeBSD is not compiled with Spotlight support (`smbd -b` does not mention Spotlight). I'll try building it from source.

**Comment by lamixer** [comment]
yes, mine does"

# smbd -b | grep SPOTLIGHT
   HAVE_SPOTLIGHT_BACKEND_ES
   WITH_SPOTLIGHT

**Comment by lamixer** [comment]
Hi.. I think mine is working now. I get the message that 'server search [is] enabled' and in the Finder I get search results back, at least for file names. I haven't tried searching for content yet. mdfind does not give me results however. I think the original problem for me was the permissions the Mac was seeing for the Samba share, being only RW for the user, not system or all.

I still had a few questions you might consider adding to the 'how to' (you may be getting more Elasticsearch noobs like myself here because you have made it to the Samba wiki [ https://wiki.samba.org/index.php/Spotlight_with_Elasticsearch_Backend ]:

Does it really work without creating a user in Elasticsearch at all? I went ahead and created a user (with full privileges!) and put that username and password in the fs2es-indexer prefs. If a user is required, what privileges should it have?

Does the index not get updated unless fs2es-indexer is run? There is no facility for a filesystem watcher in Elasticsearch?

On a systemd distro, would you recommend I create a service file to run fs2es-indexer daemon mode? Or would a cron job to run it (as a one-off, not daemon) be fine?

Thanks!

**Comment by MatthiasKuehneEllerhold** [comment]
> Hi.. I think mine is working now. I get the message that 'server search [is] enabled' and in the Finder I get search results back, at least for file names. I haven't tried searching for content yet. mdfind does not give me results however. I think the original problem for me was the permissions the Mac was seeing for the Samba share, being only RW for the user, not system or all.

Thats nice to hear!


> I still had a few questions you might consider adding to the 'how to' (you may be getting more Elasticsearch noobs like myself here because you have made it to the Samba wiki [ https://wiki.samba.org/index.php/Spotlight_with_Elasticsearch_Backend ]:
 
Issue #5 wants me to do the same. I'll think about what I can add to the README.md

> Does it really work without creating a user in Elasticsearch at all? I went ahead and created a user (with full privileges!) and put that username and password in the fs2es-indexer prefs. If a user is required, what privileges should it have?

Yes it works without a user. Thats how our instances are setup because our elastic search instances are only accessible locally (the standard config).

Privileges needed are reading and writing to the defined index (standard "files") for the indexer and reading only for samba.

> Does the index not get updated unless fs2es-indexer is run? There is no facility for a filesystem watcher in Elasticsearch?

Updates are only happening if the indexer is run. An easy way to do this is to use the daemon mode.

There is no filesystem watcher, because I couldnt get it to work - but I'd be open to a more robust implementation if you get it to work!

> On a systemd distro, would you recommend I create a service file to run fs2es-indexer daemon mode? Or would a cron job to run it (as a one-off, not daemon) be fine?

I have a full debian packaging script for this project, I'm currently evaluating if Im going to commit it here and keep it elsewhere. Would you prefer it to be included her?

A systemd service witht the indexer in daemon mode is superior to a cronjob, because the daemon mode waits for X minutens after completion of the last run - whereas a cronjob just starts a new run regardless if and when the old run was finished.

**Comment by lamixer** [comment]
Thank you for the answers, and again, thanks for your time in making this project available for us to all use.

I don't really need indexing, so I think you have me covered. It would be interesting to see the debian packaging script (here or anywhere) though I probably wouldn't use it.

Regarding systemd vs. cron, I take your point and that could be an important advantage for some people. For me, indexing runs are so fast they would always be done before I would fire it again, maybe every 30 minutes (though I could also have flock run the job to ensure it has completed in case something gets weird). I'll think about it!

**Comment by MatthiasKuehneEllerhold** [comment]
So @lamixer everything is resolved now?

**Comment by lamixer** [comment]
Thanks @MatthiasKuehneEllerhold, I think I'm all set though I haven't been using the set up in the past few weeks.
